INSERT INTO subjects (name, slug) VALUES
                                      ('Математика', 'math'),
                                      ('Физика', 'physics'),
                                      ('Химия', 'chemistry'),
                                      ('Биология', 'biology'),
                                      ('География', 'geography'),
                                      ('Тарих', 'history'),
                                      ('Қазақ тілі мен әдебиеті', 'kazakh'),
                                      ('Орыс тілі мен әдебиеті', 'russian'),
                                      ('Ағылшын тілі', 'english'),
                                      ('Бастауыш сынып', 'primary'),
                                      ('Дене шынықтыру', 'pe'),
                                      ('Еңбекке баулу', 'labor'),
                                      ('Музыка', 'music'),
                                      ('Сызу', 'drawing'),
                                      ('Бейнелеу өнері', 'fine-arts'),
                                      ('Информатика', 'informatics'),
                                      ('Алғашқы әскери дайындық', 'military'),
                                      ('Директор', 'director'),
                                      ('Оқу ісінің меңгерушісі', 'head-teacher');