spring:
  application:
    name: persons-catalog
  datasource:
    url: jdbc:postgresql://localhost:5433/persons
    username: persons
    password: persons
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

logging:
  level:
    org.hibernate.SQL: debug

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  storage:
    path: ./uploads
    base-url: http://localhost:8080/uploads